### ISSUE TITLE
AD authentication + cross platform support?

### ISSUE THREAD

**Issue by prabhu** [Fizcko/Azure_DevOps_Vault_Interaction#1]
Thanks for this plugin. Any plans to build Azure AD authentication support? Also, what is the current status of this plugin on Linux and Mac build agents?

**Comment by Fizcko** [comment]
Hi @prabhu

I will create a new version to support Azure Auth Method as soon as possible. Will you able to test this feature ?

This plugin is compatible with all platforms.

**Comment by Fizcko** [comment]
@prabhu

A new version 1.1.0 as been release on the Azure DevOps marketplace. This release include azure authentication.
You're welcome to try this new authentication method.
Feel free to add a rating and/or review.

**Comment by prabhu** [comment]
Thank you for the prompt response. Apologies for the late reply from my end. It will be sometime before I could get this tested but can understand the changes made. Thanks again.
