### ISSUE TITLE
Support for https/http proxy env variables when making requests to hashicorp vault

### ISSUE THREAD

**Issue by milanhradil-tomtom** [Fizcko/Azure_DevOps_Vault_Interaction#10]
Hi,
thanks for this extensions. I'm trying to access hashicorp vault behind https proxy but the request time out. I see that DNS record is resolved correctly to IP address but for the request is not https proxy used even if the env variable HTTPS_PROXY is set.

I think that if HTTPS_PROXY or HTTP_PROXY is set then requests should use that proxy. Proxy setting could be also implemented as connection parameter.

Thanks

**Comment by Fizcko** [comment]
Hi @milanhradil-tomtom 

I've just release a new version 3.0.0 on the Azure DevOps marketplace. This version should resolve your issue.

Let me knows if it's work or not.

Regards
