### ISSUE TITLE
Task breaks when using an approle

### ISSUE THREAD

**Issue by pecoult** [Fizcko/Azure_DevOps_Vault_Interaction#11]
Good afternoon,

We tried on our project to use the last version **(version 3)** of this Azure Devops task but there is an issue with the authentication process.

Our scenario:
- Connect to our Keyvault with an approle
=> Error we get when running the task: **TypeError: Cannot read property 'auth' of undefined**

Fallback: Our integration works correctly with the version 2.*

Issue: We had a look at the code and it seems that there is a problem with this line: https://github.com/Fizcko/Azure_DevOps_Vault_Interaction/blob/2c3056c010f45c3a70ac1b1e821c646b1b0575fe/src/common/request.ts#L243
'resultJSON' is undefined so when you try to extract the client token it breaks: resultJSON.auth.client_token

Let me know if you need more details for this issue.

Cordially,

Romain P.

**Comment by Fizcko** [comment]
Hi @pecoult,

Thanks for open this issue. It was a huge bug. #

I've just publish a new release 3.0.1 on the Azure DevOps marketplace. This version should resolve your issue.

Let me knows if it's work or not.

Regards

**Comment by pecoult** [comment]
Hi @Fizcko,
Thank you for fixing this issue in no time! I just tested the fix and it works fine now in our case (authentication with approle).

Regards
