### ISSUE TITLE
upgrade to Node10

### ISSUE THREAD

**Issue by LanceSandino** [Fizcko/Azure_DevOps_Vault_Interaction#12]
Pipelines are warning:

```
##[warning]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.
```

**Comment by Fizcko** [comment]
Hi @LanceSandino 

I've just release a new version 4.0.0 on the Azure DevOps marketplace. This version should resolve your issue.

Let me knows if it's work or not.

Regards

**Comment by LanceSandino** [comment]
perfect thank you!
![image](https://user-images.githubusercontent.com/1300195/142062423-1cd0b429-50b1-4b1f-a382-f2dec6e8b0fb.png)
