### ISSUE TITLE
Doesn’t have an integrated service connection

### ISSUE THREAD

**Issue by juvai** [Fizcko/Azure_DevOps_Vault_Interaction#16]
Hello,

to store secrets in the pipeline are the only way? I don't think that this good approach to storing secrets in the pipeline. Or maybe is it a way to use some type of service connection?

**Comment by Fizcko** [comment]
Hello,

The variables (read from Hashicorp Vault) are not stored.

They are available during the pipeline execution for been used by other tasks.

You can have more information here:
https://learn.microsoft.com/en-us/azure/devops/pipelines/process/set-variables-scripts?view=azure-devops&tabs=bash

**Comment by juvai** [comment]
I talking about secrets (credentials) that you are needed to login into Vault.
The task of the extension requires a login method, depending on the method you used it requires a username and password, token, etc. So is it the only way to reach the Vault or the Service Connection will arrive in the future?

**Comment by docbyte86** [comment]
you can use azure pipeline library variables and store them as secrets.
-> https://learn.microsoft.com/en-us/azure/devops/pipelines/process/set-secret-variables?view=azure-devops&tabs=yaml%2Cbash

**Comment by Fizcko** [comment]
Hi @juvai,

I've just publish a new release 5.0.0 on the Azure DevOps marketplace.

This version include the ability to manage some credentials with a service connection.

Regards
