### ISSUE TITLE
Vault - Read KV secrets version 5 is dependent on a Node version (10)

### ISSUE THREAD

**Issue by locduc-zenfolio** [Fizcko/Azure_DevOps_Vault_Interaction#23]
I see the warning below on Azure Pipeline, could you upgrade node version for this plugin?

`Task 'Vault - Read KV secrets' version 5 (VaultReadKV@5) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance:`

**Comment by docbyte86** [comment]
> I see the warning below on Azure Pipeline, could you upgrade node version for this plugin?
> 
> `Task 'Vault - Read KV secrets' version 5 (VaultReadKV@5) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance:`

confirmed. we get the same

**Comment by Fizcko** [comment]
Hi @locduc-zenfolio @docbyte86 ,

I've just release a new version 5.2.0 on the Azure DevOps marketplace.

This version resolve your issue.

Is it possible for you to give me a feedback ?

Thanks

**Comment by locduc-zenfolio** [comment]
Hi @Fizcko it's working well with new version 5.2.0, thanks for the quick fix

**Comment by Fizcko** [comment]
Thanks for the feedback i appreciate.
