### ISSUE TITLE
some wishes for the functional

### ISSUE THREAD

**Issue by damagedouble** [Fizcko/Azure_DevOps_Vault_Interaction#3]
Really nice extension! Respect!
But important checkbox field "prefix" is bad way for me
I changed code, but if possible please change this option in next release;)

Also sometimes i need get 300+ keys for my environment.
I created hard "task group" in my TFS

If will possible get all keys from folder in future - i well be happy :)

**Comment by Fizcko** [comment]
Hi @damagedouble,

I don't understand your request. Can you give me more explanations or/and examples.

> field "prefix" is bad way for me
You need a optional prefix field ?

> If will possible get all keys from folder in future
You want a feature that return secrets from a vault folder ?

**Comment by damagedouble** [comment]
Thanks for the quick response!

> You need a optional prefix field ?

Yes, Field prefix is required:
Specifies prefix of the variables. Variables will be named PREFIX_VariableName.

I have a ready infrastructure (with the names of more than 300 variables) - the prefix hinders much
I turned it off (hardcode), but I would really like this option to be in the official release

> You want a feature that return secrets from a vault folder ?

Yes, I would really like to be able to read all the keys in the folder

since I have a lot of them, I have to create a lot of tasks in the group for reading :)

but still the extention is awesome!

**Comment by Fizcko** [comment]
Ok i have understand all your needs. 
I will release a new version as soon as possible.

**Comment by damagedouble** [comment]
Hi Fizcko!

Can You explain me please, how you do build extension?

command
**tfx extension create --manifest-globs vss-extension.json**

create fie *vsix, i install it to TFS but  in deploy task have error:
**2019-07-30T09:36:46.1646921Z ##[error]File not found: '/vsts/agent/_work/_tasks/VaultReadKV_807a85d5-8ac9-4b8c-a0fc-1b233bb2bc77/1.1.8/kv_read.js''**

also if i try create build using powershell file build_job.ps1
extensions is create, but i have errors like this:

**PS /home/iurii/DEVOPS/Azure_DevOps_Vault_Interaction-master> ./build_job.ps1
[INFO] New version : '1.1.21'
VaultReadKV@ /home/iurii/DEVOPS/Azure_DevOps_Vault_Interaction-master/dist/kv_read
└─┬ azure-pipelines-task-lib@2.8.0 
  ├─┬ minimatch@3.0.4 
  │ └─┬ brace-expansion@1.1.11 
  │   ├── balanced-match@1.0.0 
  │   └── concat-map@0.0.1 
  ├── mockery@1.7.0 
  ├── q@1.5.1 
  ├── semver@5.7.0 
  ├── shelljs@0.3.0 
  └── uuid@3.3.2 

Copy-Item : Cannot find path '/home/iurii/DEVOPS/Azure_DevOps_Vault_Interaction-master/dist/common' because it does not exist.
At /home/iurii/DEVOPS/Azure_DevOps_Vault_Interaction-master/build_job.ps1:95 char:5
+     Copy-Item -Path "$pathCommon" -Destination "$subProjectPath" -Rec ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (/home/iurii/DEVOPS/\u2026-master/dist/common:String) [Copy-Item], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand
 
Remove-Item : Cannot find path '/home/iurii/DEVOPS/Azure_DevOps_Vault_Interaction-master/dist/common' because it does not exist.
At /home/iurii/DEVOPS/Azure_DevOps_Vault_Interaction-master/build_job.ps1:99 char:1
+ Remove-Item -Path "$pathCommon" -Recurse -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (/home/iurii/DEVOPS/\u2026-master/dist/common:String) [Remove-Item], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
 
TFS Cross Platform Command Line Interface v0.7.8
Copyright Microsoft Corporation

=== Completed operation: create extension ===
**

build task removes folder even if i put her there :)

**Comment by Fizcko** [comment]
I will release the extension during this day. I just have to finish the documentations (overview.md).

This new release will included your both requirements.

**Comment by Fizcko** [comment]
@damagedouble i have just publish a release 2.0.0 on the marketplace.

Please have make a try to this new version.

The source code will be commit in soon.

**Comment by damagedouble** [comment]
@Fizcko THANKS!!!
**Awesome! So fast!
thank you very much!**

Now it's much more convenient.
You made my job much easier
and I hope users will also appreciate this addition!

if possible, please add instructions to file **overview.md**
how build this project, like this:

prepare:
- npm install 
- npm install -g typescript 
- npm install azure-pipelines-task-lib --save

build:
- tsc -p .\tsconfig.json
- tsc build .\tsconfig.json
- ./build_job.ps1  or (-tfx extension create --manifest-globs vss-extension.json)

NICE!

**Comment by damagedouble** [comment]
I think the previous version did not generate variables in capital letters

as well as in the log variables were not displayed in the open
like here:
[VAR_DISABLE_NOTIFICATIONS] -> [false]
[VAR_ENABLE_DB_MIGRATION] -> [false]


there used to be something like key in VAULT
[Var_Disable_Notifications] -> [*****]
[Var_Enable_db_Migration] -> [*****]

**Comment by Fizcko** [comment]
Thanks for the return.

The case (Upper case, lower case) did not change. The case is taken directly from Vault output.

I don't understand your request.

**Comment by damagedouble** [comment]
Sorry,
This is my mistake I did not manage to delete the message
You are too fast :)

Thank you very much!
