### ISSUE TITLE
Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by damagedouble** [Fizcko/Azure_DevOps_Vault_Interaction#5]
Hi @Fizcko !

Your plugin works great!

But I ran into one problem
Since I get a lot of variables
sometimes I get like this error:

2019-08-06T13:28:05.6311956Z ##[error]Error during browsing engine. Error when requesting Vault '********v1/xxxxx/data/xxx/xxxxxx/xxxxxxxxx' : Error: connect ETIMEDOUT xxx.xx.xx.xxx:443

it doesn't happen often
but it is very important

if the release has fallen on the second buildagent when reading keys
release - half :)
an urgent return to a previous state can also fall

Is there any way to increase the timeout?

**Comment by Fizcko** [comment]
Hi @damagedouble 

I will add a new field to  set the timeout

**Comment by Fizcko** [comment]
@damagedouble 

I've just release a new version 2.2.0

**Comment by Fizcko** [comment]
@damagedouble

If this fix do not solve the problem you can add the setting 'default_max_request_duration' in vault server configuration.

https://www.vaultproject.io/docs/configuration/index.html#default_max_request_duration

**Comment by damagedouble** [comment]
Great!
You have such cool support!
I feel like I bought an expensive plugin :)

I would give you 100 stars if I could
I will ask my colleagues to do this :)
