### ISSUE TITLE
Vault Namespaces

### ISSUE THREAD

**Issue by quantumew** [Fizcko/Azure_DevOps_Vault_Interaction#8]
Are vault namespaces supported? At a cursory glance, it appears not. Either all paths must be mutable, in order to add the namespace as a prefix to every path or the header `X-Vault-Namespace` needs to be sent. For instance, I am using AppRole auth and I see no way to authenticate properly on a Vault Namespace.

**Comment by Fizcko** [comment]
Hi @quantumew 

I've just release a new version 2.4.0 on the Azure DevOps marketplace to manage namespaces.

Unfortunatly i don't have an Enterprise version to test it.

Reading the documentation, i thinks that will work in a single namespace.

Let me knows if it's work or not.

Regards

**Comment by quantumew** [comment]
Blazing fast feature addition! I am on an on-premise Azure DevOps so it will take a while to get this extension updated and tested. I will let you know! Based on your code, it looks good.

**Comment by StevenKuhns** [comment]
@quantumew have you been able to see if namespaces works for you with the latest version?

**Comment by quantumew** [comment]
Never circled back. This worked.
