### ISSUE TITLE
Multiline secret example request. 

### ISSUE THREAD

**Issue by binario200** [Fizcko/Azure_DevOps_Vault_Interaction#9]
Hi 
Thanks for sharing your Vault Interaction Azure Devops extension is very handy. Now I am storing certificates in Hashicorp Vault but I am having the "Secrets cannot contain multiple lines" error at my azure pipeline when I try to retrieve the cert secret using your extension. 

I know that you included the replaceCR and the carriage return token options but I think I did not get how to use it. Do you know where I can find an example?

My question is: if I replace carriage returns let's say with  '#{rn}#'  this will allow injecting the certificate secret as variable in the azure pipeline, but later how to get back the carriage returns to have a valid and usable certificate? 

Thanks in advance

**Comment by Fizcko** [comment]
Hi @binario200,

Thanks for using my extension.

The main goal is to create a file with your variable.

When the file is created the content will be like "line one#{rn}#line two ..."

Then you have to parse the file and replace '#{rn}#' by a carriage return.

I will add a task to perform this kind of action: create a file from a variable and replace the token by carriage return.

I come back to you as soon as it's done.

**Comment by Fizcko** [comment]
@binario200 ,

I just released a new version 2.5.0 on the Azure DevOps marketplace.
The extension includes now a second task called “Tool - Create a File”.

There is two use case examples in the extension overview.
Hope this will help you.
